# 错误处理

## 简介

rust中错误分为两大类:可恢复的和不可恢复的.
rust使Result类型处理可恢复的错误,panic!宏处理不可恢复的错误.

## panic

panic!宏会导致程序崩溃,并输出错误信息.
一般有两种使用方式:

1. 执行了会导致panic的操作,比如越界访问数组
2. 手动调用panic!宏

panic!会打印一个错误信息,展开并清理站数据,然后退出程序.

简单的使用方法如下:

```rust
fn main() {
    panic!("crash and burn");
}
```

在实际使用中可以通过设置命令行参数RUST_BACKTRACE=1来打印详细的错误信息.

## Result

```rust
use std::fs::File;
use std::io::ErrorKind;
enum Result<T, E> {
    Ok(T),
    Err(E),
} 
//Result<T,E>是一个枚举类型,包含两个泛型参数T,E.
//T代表成功时返回的Ok值,E代表失败时返回的Err值.


fn main() {
    let greeting_file_result = File::open("hello.txt");
    /*
    File::open()函数返回一个Result<T,E>类型的值,其中T是File类型,E是io::Error类型.
    即打开成功时返回文件的句柄,失败时返回一个io::Error类型的错误.
     */

    //处理Result<T,E>类型的值
    let greeting_file = match greeting_file_result {
        Ok(file)=>file,
        Err(error)=>panic!("Problem opening the file: {error:?}"),
    };
}
```

### 匹配不同的错误

上面的代码不论什么情况下都会panic,现在希望可以针对不同的错误原因给出不同的解决方法

```rust
    let greeting_file = match greeting_file_result {
        Ok(file)=>file,
        Err(error)=> match error.kind() {
            ErrorKind::NotFound => match  File::create("hello.txt") {
                Ok(fc)=>fc,
                Err(e)=>panic!("Problem create file:{e:?}"),
            }
            other_error=>{panic!("Problem opening the file {other_error:?}");}
        }
    };
```

### 简化错误处理,使用unwrap和expect

Result<T,E>类型定义了unwrap方法,如果Result是Ok,则返回Ok中的值,否则调用panic!宏.

```rust
    let greeting_file = File::open("hello.txt").unwrap();
```

如果调用代码时不存在hello.txt文件,则会调用panic宏.

expect方法和unwrap方法类似,但是可以自定义错误信息.

```rust
    let greeting_file = File::open("hello.txt").expect("Failed to open hello.txt");
```

## 传播错误

在函数中处理错误时,既可以选择在函数中处理错误,也可以将错误传播给调用者处理.

```rust
#![allow(unused)]
fn main() {
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let username_file_result = File::open("hello.txt");

    let mut username_file = match username_file_result {
        Ok(file) => file,
        Err(e) => return Err(e),//如果发生错误,则返回错误,退出函数
    };

    let mut username = String::new();

    match username_file.read_to_string(&mut username) {
        Ok(_) => Ok(username),
        Err(e) => Err(e),
    }
}
}
```

## ?操作符

上面的代码中,如果发生错误,则返回错误,退出函数.这样的代码会导致大量的重复代码,可以使用?操作符简化代码.

```rust
use std::fs::File;
use std::io::{self,Read};

fn read_username_from_file() -> Result<String,io::Error> {
    let mut username_file=File::open("hello.txt")?;
    let mut username = String::new();
    username_file.read_to_string(&mut username)?;
    Ok(username)
}
```

?运算符实现了上面代码中的match表达式,如果Result是Ok,则返回Ok中的值,否则将错误传播给调用者.
?运算符可以进行链式调用,如果发生错误,则会立即返回错误.

```rust
fn read_username_from_file() -> Result<String,io::Error> {
    let mut username = String::new();
    File::open("hello.txt")?.read_to_string(&mut username)?;
    Ok(username)
}
```

需要注意的是:

1. ?操作符只能用于返回Result的函数,也可用于返回Option的函数
2. ?操作符会自动将错误类型转换为函数返回类型的错误类型,但前提是两者可以转换

## panic!还是Result?

1. 示例,测试中适合用panic
2. 如果能确定Result的结果是Ok的话,那么使用expect或unwrap
3. 如果会导致有害的情况,那么使用panic
